### ISSUE TITLE
Crear modelo ORM

### ISSUE THREAD

**Issue by espinoza** [MartinSchere/BlogIntegracion#2]
Creo que el siguiente paso es crear el archivo `models.py`.

![image](https://user-images.githubusercontent.com/42013600/112658734-75280c80-8e32-11eb-8e0a-99e9b414d2c9.png)

¿Lo hacemos entre varios o alguien desea comenzar por su cuenta?

**Comment by MartinSchere** [comment]
Podemos hacer un modelo cada uno

**Comment by espinoza** [comment]
> Podemos hacer un modelo cada uno

De acuerdo.

**Comment by Guerra-Defranchi** [comment]
Me anoto con uno de los 4 modelos. Consulta: Vamos a utilizar django forms para el proyecto o la manera clásica?

**Comment by MartinSchere** [comment]
@Guerra-Defranchi Vamos a hacer lo que más prefieran!

**Comment by espinoza** [comment]
Ya hemos creado el modelo, está en la rama master. Ver commit #5. Se consideraron los cambios de #4 realizados por @Guerra-Defranchi.
